#!/bin/bash

declare -A KPLATFORM_ARRAY=(
    ["taro"]="LA.VENDOR.1.0.r1-26900-WAIPIO.QSSI15.0"
    ["kalama"]="LA.VENDOR.13.2.0.r1-25900-KAILUA.QSSI15.0"
    ["pineapple"]="AU_LINUX_ANDROID_LA.VENDOR.14.3.0.R1.00.00.00.000.160"
)
